"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.get1DDataXY = exports.generateSpectrumFromRanges = exports.mapRanges = exports.updateXShift = exports.changeRangeRelativeValue = exports.changeRange = exports.detectRange = exports.detectRanges = exports.changeRangeSignal = exports.addRange = exports.changeIntegralsRelative = exports.updateRangesRelativeValues = exports.updateIntegralsRelativeValues = exports.getReferenceShift = exports.generateSpectrumFromPublicationString = exports.isSpectrum1D = exports.checkIntegralKind = exports.checkRangeKind = exports.lookupPeak = exports.getShiftX = exports.autoPeakPicking = exports.toJSON = exports.initiateDatum1D = void 0;
const generateSpectrumFromPublicationString_1 = require("./generateSpectrumFromPublicationString");
Object.defineProperty(exports, "generateSpectrumFromPublicationString", { enumerable: true, get: function () { return generateSpectrumFromPublicationString_1.generateSpectrumFromPublicationString; } });
const get1DDataXY_1 = require("./get1DDataXY");
Object.defineProperty(exports, "get1DDataXY", { enumerable: true, get: function () { return get1DDataXY_1.get1DDataXY; } });
const getReferenceShift_1 = require("./getReferenceShift");
Object.defineProperty(exports, "getReferenceShift", { enumerable: true, get: function () { return getReferenceShift_1.getReferenceShift; } });
const initiateDatum1D_1 = require("./initiateDatum1D");
Object.defineProperty(exports, "initiateDatum1D", { enumerable: true, get: function () { return initiateDatum1D_1.initiateDatum1D; } });
const changeIntegralsRelative_1 = require("./integrals/changeIntegralsRelative");
Object.defineProperty(exports, "changeIntegralsRelative", { enumerable: true, get: function () { return changeIntegralsRelative_1.changeIntegralsRelative; } });
const checkIntegralKind_1 = require("./integrals/checkIntegralKind");
Object.defineProperty(exports, "checkIntegralKind", { enumerable: true, get: function () { return checkIntegralKind_1.checkIntegralKind; } });
const updateIntegralsRelativeValues_1 = require("./integrals/updateIntegralsRelativeValues");
Object.defineProperty(exports, "updateIntegralsRelativeValues", { enumerable: true, get: function () { return updateIntegralsRelativeValues_1.updateIntegralsRelativeValues; } });
const isSpectrum1D_1 = require("./isSpectrum1D");
Object.defineProperty(exports, "isSpectrum1D", { enumerable: true, get: function () { return isSpectrum1D_1.isSpectrum1D; } });
const autoPeakPicking_1 = require("./peaks/autoPeakPicking");
Object.defineProperty(exports, "autoPeakPicking", { enumerable: true, get: function () { return autoPeakPicking_1.autoPeakPicking; } });
const lookupPeak_1 = require("./peaks/lookupPeak");
Object.defineProperty(exports, "lookupPeak", { enumerable: true, get: function () { return lookupPeak_1.lookupPeak; } });
const addRange_1 = require("./ranges/addRange");
Object.defineProperty(exports, "addRange", { enumerable: true, get: function () { return addRange_1.addRange; } });
const changeRange_1 = require("./ranges/changeRange");
Object.defineProperty(exports, "changeRange", { enumerable: true, get: function () { return changeRange_1.changeRange; } });
const changeRangeRelativeValue_1 = require("./ranges/changeRangeRelativeValue");
Object.defineProperty(exports, "changeRangeRelativeValue", { enumerable: true, get: function () { return changeRangeRelativeValue_1.changeRangeRelativeValue; } });
const changeRangeSignal_1 = require("./ranges/changeRangeSignal");
Object.defineProperty(exports, "changeRangeSignal", { enumerable: true, get: function () { return changeRangeSignal_1.changeRangeSignal; } });
const checkRangeKind_1 = require("./ranges/checkRangeKind");
Object.defineProperty(exports, "checkRangeKind", { enumerable: true, get: function () { return checkRangeKind_1.checkRangeKind; } });
const detectRange_1 = require("./ranges/detectRange");
Object.defineProperty(exports, "detectRange", { enumerable: true, get: function () { return detectRange_1.detectRange; } });
const detectRanges_1 = require("./ranges/detectRanges");
Object.defineProperty(exports, "detectRanges", { enumerable: true, get: function () { return detectRanges_1.detectRanges; } });
const generateSpectrumFromRanges_1 = require("./ranges/generateSpectrumFromRanges");
Object.defineProperty(exports, "generateSpectrumFromRanges", { enumerable: true, get: function () { return generateSpectrumFromRanges_1.generateSpectrumFromRanges; } });
const mapRanges_1 = require("./ranges/mapRanges");
Object.defineProperty(exports, "mapRanges", { enumerable: true, get: function () { return mapRanges_1.mapRanges; } });
const updateRangesRelativeValues_1 = require("./ranges/updateRangesRelativeValues");
Object.defineProperty(exports, "updateRangesRelativeValues", { enumerable: true, get: function () { return updateRangesRelativeValues_1.updateRangesRelativeValues; } });
const getShiftX_1 = require("./shift/getShiftX");
Object.defineProperty(exports, "getShiftX", { enumerable: true, get: function () { return getShiftX_1.getShiftX; } });
const updateXShift_1 = require("./shift/updateXShift");
Object.defineProperty(exports, "updateXShift", { enumerable: true, get: function () { return updateXShift_1.updateXShift; } });
const toJSON_1 = require("./toJSON");
Object.defineProperty(exports, "toJSON", { enumerable: true, get: function () { return toJSON_1.toJSON; } });
